framework:
    messenger:
        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    auto_setup: false
                    exchange:
                        name: messages
                        type: direct
                        default_publish_routing_key: from_app2
                    queues:
                        messages:
                            binding_keys: [from_app2]

        routing:
            'App\Message\StatusUpdate': async